name: Build Kintone Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create private key file
      env:
        PLUGIN_PRIVATE_KEY: ${{ secrets.PLUGIN_PRIVATE_KEY }}
      run: |
        echo "$PLUGIN_PRIVATE_KEY" > ienmacjkmpbhkikakmnieiekgemiloaj.ppk
    
    - name: Build plugin
      run: npm run package
    
    - name: Rename plugin file
      run: mv plugin.zip kintone-word-collector.zip
    
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: kintone-word-collector-plugin
        path: kintone-word-collector.zip
        retention-days: 30
    
    - name: Create Release on main branch
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Kintone Word Collector Plugin
          
          日本語文章の表記ゆれや不適切な表現をチェック・修正提案するKintoneプラグインです。
          
          ### 機能
          - 67個の表記ゆれチェック
          - 保存時の自動置換ダイアログ
          - フィールド選択可能な設定画面
          
          ### インストール方法
          1. `kintone-word-collector.zip` をダウンロード
          2. Kintone管理画面でプラグインをアップロード
          3. アプリにプラグインを追加して設定
          
          ---
          Copyright (c) 2025 wadatch
          Licensed under the MIT License
        files: kintone-word-collector.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}