name: Release Plugin

on:
  push:
    branches: [ main ]
    # Only trigger on merge commits from pull requests
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  check-merge-commit:
    runs-on: ubuntu-latest
    outputs:
      is-merge: ${{ steps.check.outputs.is-merge }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Check if this is a merge commit
      id: check
      run: |
        # Check if this commit has more than one parent (merge commit)
        if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
          parents=$(git cat-file -p HEAD | grep "^parent " | wc -l)
          if [ $parents -gt 1 ]; then
            echo "is-merge=true" >> $GITHUB_OUTPUT
            echo "This is a merge commit"
          else
            echo "is-merge=false" >> $GITHUB_OUTPUT
            echo "This is not a merge commit"
          fi
        else
          echo "is-merge=false" >> $GITHUB_OUTPUT
          echo "This is the first commit"
        fi

  release:
    needs: check-merge-commit
    if: needs.check-merge-commit.outputs.is-merge == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create private key file
      env:
        PLUGIN_PRIVATE_KEY: ${{ secrets.PLUGIN_PRIVATE_KEY }}
      run: |
        echo "$PLUGIN_PRIVATE_KEY" > ienmacjkmpbhkikakmnieiekgemiloaj.ppk
    
    - name: Build plugin
      run: npm run package
    
    - name: Rename plugin file
      run: mv plugin.zip kintone-word-collector.zip
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Kintone Word Collector Plugin
          
          日本語文章の表記ゆれや不適切な表現をチェック・修正提案するKintoneプラグインです。
          
          ### 機能
          - 67個の表記ゆれチェック
          - 保存時の自動置換ダイアログ
          - フィールド選択可能な設定画面
          
          ### インストール方法
          1. `kintone-word-collector.zip` をダウンロード
          2. Kintone管理画面でプラグインをアップロード
          3. アプリにプラグインを追加して設定
          
          ### 変更内容
          ${{ github.event.head_commit.message }}
          
          ---
          Copyright (c) 2025 wadatch
          Licensed under the MIT License
        files: kintone-word-collector.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}